drop table IF EXISTS users CASCADE;
create TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(50) unique NOT NULL,
    password varchar(200) unique NOT NULL
);

drop table IF EXISTS authorities CASCADE;
create TABLE IF NOT EXISTS authorities (
    user_id BIGINT REFERENCES users(user_id) ON delete CASCADE,
    authority varchar(20)
);

drop table IF EXISTS avatars CASCADE;
create TABLE IF NOT EXISTS avatars (
    avatar_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(250) NOT NULL,
    type varchar(50) NOT NULL,
    link varchar(1000) NOT NULL
);

drop table IF EXISTS profile CASCADE;
create TABLE IF NOT EXISTS profile (
    name varchar(200),
    last_name varchar(200),
    sur_name varchar(200),
    phone varchar(200) unique,
    birthday DATE,
    gender varchar(20),
    country varchar(200),
    region varchar(200),
    city varchar(200),
    citizenship varchar(200),
    user_id BIGINT REFERENCES users(user_id) ON delete CASCADE NOT NULL,
    avatar_id BIGINT REFERENCES avatars(avatar_id) ON delete CASCADE unique,
    about varchar,
    is_child BOOLEAN,
    is_child_expert BOOLEAN,
    PRIMARY KEY (user_id)
);

drop table IF EXISTS subscriptions CASCADE;
create TABLE IF NOT EXISTS subscriptions (
    subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES profile(user_id) ON delete CASCADE,
    subscriber_id BIGINT REFERENCES profile(user_id) ON delete CASCADE
);

drop table IF EXISTS social_network_links CASCADE;
create TABLE IF NOT EXISTS social_network_links (
    user_id BIGINT REFERENCES profile(user_id) ON delete CASCADE,
    link varchar(1000)
);

drop table IF EXISTS publications CASCADE;
create TABLE IF NOT EXISTS publications (
    publication_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES profile(user_id) ON delete CASCADE,
    title varchar(250) NOT NULL,
    type varchar(50) NOT NULL,
    link varchar(1000) NOT NULL,
    description varchar(5000)
);

drop table IF EXISTS events CASCADE;
create TABLE IF NOT EXISTS events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type varchar(200),
    title varchar(200)
);

drop table IF EXISTS event_images CASCADE;
create TABLE IF NOT EXISTS event_images (
    event_image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(event_id) ON delete CASCADE,
    title varchar(250) NOT NULL,
    type varchar(50) NOT NULL,
    link varchar(1000) NOT NULL
);

drop table IF EXISTS grand_final_events CASCADE;
create TABLE IF NOT EXISTS grand_final_events (
    grand_final_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grand_final_event_date DATE,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    description varchar(1000),
    event_type varchar(200),
    title varchar(200),
    location varchar(200)
);

drop table IF EXISTS grand_final_event_directions CASCADE;
create TABLE IF NOT EXISTS grand_final_event_directions (
   grand_final_event_id BIGINT REFERENCES grand_final_events(grand_final_event_id) ON delete CASCADE,
   direction varchar(100)
);

drop table IF EXISTS user_requests CASCADE;
create TABLE IF NOT EXISTS user_requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200),
    last_name varchar(200),
    sur_name varchar(200),
    phone varchar(200),
    birthday DATE,
    gender varchar(20),
    email varchar(200),
    address varchar(200),
    created TIMESTAMP,
    status varchar(200),
    type_of_selection varchar(200),
    user_id BIGINT REFERENCES profile(user_id) ON delete CASCADE NOT NULL,
    event_id BIGINT REFERENCES events(event_id) ON delete CASCADE,
    grand_final_event_id BIGINT REFERENCES grand_final_events(grand_final_event_id) ON delete CASCADE
);

drop table IF EXISTS request_preview CASCADE;
create TABLE IF NOT EXISTS request_preview (
    request_preview_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT REFERENCES user_requests(request_id) ON delete CASCADE unique,
    title varchar(250) NOT NULL,
    type varchar(50) NOT NULL,
    link varchar(1000) NOT NULL
);

drop table IF EXISTS user_request_directions CASCADE;
create TABLE IF NOT EXISTS user_request_directions (
   request_id BIGINT REFERENCES user_requests(request_id) ON delete CASCADE,
   direction varchar(100)
);

drop table IF EXISTS request_social_network_links CASCADE;
create TABLE IF NOT EXISTS request_social_network_links (
    request_id BIGINT REFERENCES user_requests(request_id) ON delete CASCADE,
    link varchar(1000)
);

drop table IF EXISTS news_banner CASCADE;
create TABLE IF NOT EXISTS news_banner (
    news_banner_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link varchar(1000),
    title varchar,
    type varchar
);

drop table IF EXISTS news CASCADE;
create TABLE IF NOT EXISTS news (
    news_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar,
    created TIMESTAMP,
    title varchar,
    event_time TIMESTAMP,
    banner_id BIGINT REFERENCES news_banner(news_banner_id)
);

drop table IF EXISTS profile_seasons cascade;
create TABLE IF NOT EXISTS profile_seasons (
    user_id BIGINT REFERENCES profile(user_id) ON delete CASCADE,
    season varchar(50)
);

drop table IF EXISTS profile_directions cascade;
create TABLE IF NOT EXISTS profile_directions (
    user_id BIGINT REFERENCES profile(user_id) ON delete CASCADE,
    direction varchar(50)
);

drop table IF EXISTS documents;
create TABLE IF NOT EXISTS documents (
    document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(1000),
    type varchar(50),
    link varchar(500)
);

drop table IF EXISTS resources;
create TABLE IF NOT EXISTS resources (
    resource_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(1000),
    type varchar(50),
    link varchar(500)
);

create TABLE IF NOT EXISTS feed_media (
    feed_media_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(1000),
    type varchar(50),
    link varchar(500)
);

create TABLE IF NOT EXISTS feed (
    feed_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT REFERENCES profile (user_id) ON delete CASCADE,
    media_id BIGINT REFERENCES feed_media(feed_media_id) ON delete CASCADE,
    description varchar,
    created timestamp
);

create TABLE IF NOT EXISTS feed_likes (
    feed_id BIGINT REFERENCES feed (feed_id) ON delete CASCADE,
    user_id BIGINT REFERENCES profile (user_id) ON delete CASCADE
);

create TABLE IF NOT EXISTS comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT REFERENCES profile (user_id) ON delete CASCADE,
    feed_id BIGINT REFERENCES feed (feed_id) ON delete CASCADE,
    text varchar,
    created timestamp
);

create TABLE IF NOT EXISTS comment_replies (
    comment_id BIGINT REFERENCES comments(comment_id),
    reply_id BIGINT REFERENCES comments(comment_id)
);

create TABLE IF NOT EXISTS comment_likes (
    comment_id BIGINT REFERENCES comments(comment_id),
    user_id BIGINT REFERENCES profile (user_id)
);