DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(50) unique NOT NULL,
    password varchar(200) unique NOT NULL
);

DROP TABLE IF EXISTS authorities CASCADE;
CREATE TABLE IF NOT EXISTS authorities (
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    authority varchar(20)
);

DROP TABLE IF EXISTS profile CASCADE;
CREATE TABLE IF NOT EXISTS profile (
    name varchar(200),
    last_name varchar(200),
    sur_name varchar(200),
    phone varchar(200) unique,
    birthday DATE,
    gender varchar(20),
    country varchar(200),
    region varchar(200),
    city varchar(200),
    citizenship varchar(200),
    user_id BIGINT REFERENCES users(user_id) ON DELETE RESTRICT NOT NULL,
    PRIMARY KEY (user_id)
);

DROP TABLE IF EXISTS subscribers CASCADE;
CREATE TABLE IF NOT EXISTS subscribers (
    user_id BIGINT REFERENCES profile(user_id) ON DELETE CASCADE,
    friend_id BIGINT REFERENCES profile(user_id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS social_network_links CASCADE;
CREATE TABLE IF NOT EXISTS social_network_links (
    user_id BIGINT REFERENCES profile(user_id) ON DELETE CASCADE,
    link varchar(1000)
);

DROP TABLE IF EXISTS avatars CASCADE;
CREATE TABLE IF NOT EXISTS avatars (
    avatar_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES profile(user_id) ON DELETE CASCADE NOT NULL unique,
    title varchar(250) NOT NULL,
    type varchar(50) NOT NULL,
    link varchar(1000) NOT NULL
);

DROP TABLE IF EXISTS publications CASCADE;
CREATE TABLE IF NOT EXISTS publications (
    publication_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES profile(user_id) ON DELETE CASCADE,
    title varchar(250) NOT NULL,
    type varchar(50) NOT NULL,
    link varchar(1000) NOT NULL,
    description varchar(5000)
);
