package ru.kardo.model.enums;

public enum EventType {

    GRAND_FINAL, VIDEO_CHALLENGE, CHILDREN, COMPETITIONS, AWARD, PROJECTS,
    LEISURE_PROGRAM, ENTERTAINMENT_PROGRAM, STREET_CULTURE_AND_SPORTS_PROGRAM
}
